# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('monday', models.NullBooleanField()),
                ('tuesday', models.NullBooleanField()),
                ('wednesday', models.NullBooleanField()),
                ('thursday', models.NullBooleanField()),
                ('friday', models.NullBooleanField()),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('chat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duedate', models.DateField()),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoodle.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoodle.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='Ten digit phone number, no dashes', max_length=10)),
                ('office', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=100)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoodle.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.CharField(help_text='8 digit Student ID number', max_length=8, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('classes', models.ManyToManyField(to='spoodle.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(help_text='Enter a task you have to do.', max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoodle.Student')),
            ],
        ),
    ]
