# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spoodle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoodle.Class')),
            ],
        ),
    ]
