# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spoodle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=144)),
                ('time', models.DateTimeField()),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoodle.Class')),
            ],
        ),
    ]
