# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoodle', '0003_auto_20171024_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='start',
        ),
        migrations.AddField(
            model_name='class',
            name='monday',
            field=models.NullBooleanField(),
        ),
    ]
