# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoodle', '0003_auto_20171128_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatpost',
            old_name='classes',
            new_name='classs',
        ),
        migrations.RemoveField(
            model_name='class',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='class',
            name='id',
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
