# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoodle', '0004_auto_20171026_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='friday',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='class',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='thursday',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='class',
            name='tuesday',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='class',
            name='wednesday',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
