# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spoodle', '0003_auto_20171024_1746'),
        ('spoodle', '0005_auto_20171026_1333'),
    ]

    operations = [
    ]
