# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spoodle', '0006_merge_20171031_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='professor',
        ),
        migrations.AddField(
            model_name='professor',
            name='classes',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='spoodle.Class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
